[build]
  command = "npm run build"
  publish = "out" # for `next export` or use `.next` with adapter
  # If using the @netlify/next plugin, `publish = ".next"` is fine

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
